GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlciIsImlhdCI6MTY2NzM3NjMxMSwiZXhwIjoxNjY3Mzc2MzI2fQ.Lwy-gd_0HWE2ysw-VU1Cxo522XqULwhvxhJ22hyDZCU
###
POST http://localhost:4000/login 
Content-Type: application/json

{
    "username":"user"
}
###
POST http://localhost:4000/token 
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlciIsImlhdCI6MTY2NzM3NjE5OX0.gcNmAhGYL0qAfnIKbFz3HHMMFzlc5ifyoYcRCuIytwg"
}
###
DELETE  http://localhost:4000/logout
Content-Type: application/json

{
     "token" :"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNlciIsImlhdCI6MTY2NzM3NjE5OX0.gcNmAhGYL0qAfnIKbFz3HHMMFzlc5ifyoYcRCuIytwg"
}